// Map of common passwords for O(1) lookup
export const commonPasswords: Record<string, boolean> = {
  "password": true,
  "123456": true,
  "123456789": true,
  "12345678": true,
  "12345": true,
  "1234567": true,
  "password123": true,
  "1234567890": true,
  "qwerty": true,
  "abc123": true,
  "111111": true,
  "123123": true,
  "admin": true,
  "letmein": true,
  "welcome": true,
  "monkey": true,
  "dragon": true,
  "master": true,
  "sunshine": true,
  "princess": true,
  "password1": true,
  "qwerty123": true,
  "welcome123": true,
  "admin123": true,
  "iloveyou": true,
  "trustno1": true,
  "000000": true,
  "654321": true,
  "superman": true,
  "batman": true,
  "football": true,
  "baseball": true,
  "basketball": true,
  "soccer": true,
  "passw0rd": true,
  "p@ssword": true,
  "password!": true,
  "Pass1234": true,
  "Password1": true,
  "Password123": true,
  "qwertyuiop": true,
  "asdfghjkl": true,
  "zxcvbnm": true,
  "1q2w3e4r5t": true,
  "qazwsx": true,
  "qweasd": true,
  "shadow": true,
  "michael": true,
  "jennifer": true,
  "computer": true,
  "test": true,
  "test123": true,
  "testing": true,
  "1qaz2wsx": true,
  "123qwe": true,
  "qwe123": true,
  "default": true,
  "root": true,
  "administrator": true,
  "changeme": true,
  "password1234": true,
  "Password1234": true,
  "qwerty12345": true,
  "qwerty123456": true,
  "abcd1234": true,
  "1234qwer": true,
  "qwer1234": true,
  "passw0rd123": true,
  "P@ssw0rd": true,
  "P@ssw0rd123": true,
  "P@ssword123": true,
};

export const isCommonPassword = (password: string): boolean => {
  return commonPasswords[password.toLowerCase()] === true;
};
